language: python

python: 2.7



before_install:
  - pip install tox
  - cd 06source_code
  
install: ant compile

script: 
    echo "hello"

addons:
  apt:
    packages:
      - oracle-java8-installer
        
notifications:
  email:
    - 18652005280@126.com