security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: ${STATISTICS_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:16003/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     url: jdbc:mysql://192.168.0.9:3306/piggy
     username: root
     password: Ctt=19931101
     driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations=classpath: classpath:mybatis/mysql/*.xml

server:
  context-path: /statistics
  port: 16005

rates:
  url: http://api.fixer.io