spring:
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource
     url: jdbc:mysql://192.168.0.9:3306/piggy
     username: root
     password: Ctt=19931101
     driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations=classpath: classpath:mybatis/mysql/*.xml

server:
  context-path: /uaa
  port: 5000
